### ISSUE TITLE
result.hpp fails to compile in Visual Studio 2019 (16.3.3)

### ISSUE THREAD

**Issue by mmacagno** [Dobiasd/FunctionalPlus#159]
Hello
I tried to compile with /std:c++17 and /std:c++latest but I get the same error.

This was not happening with previous versions of Visual Studio 2019. Not sure what the problem and/or fix could be.

Error C2643: FOut is not a class or namespace name

In result.hpp lines 316, 323 (6 errors total).
It craps on  GOut, which uses FOut internally.

thanks for your attention.
mac

**Comment by Dobiasd** [comment]
Ahh, that's weird.

I just tried to find out more about this `Compiler error C2643`, but all [the official docs](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-errors-c2600-through-c2699?view=vs-2019) currently have to say about this is: `Obsolete.` :grin:

![6LcECXT](https://i.imgur.com/6LcECXT.png)

So I, very boldly, say: I guess this is a compiler bug.

- Which exact version are you using?
- Is there any more context around the error you are showing?
- Can you provide a minimal example code on how to reproduce the error? Does it only happen when the template is instantiated with certain types?

If we manage to create a minimal example, we might be able to isolate it completely from FunctionalPlus. Then we could post it on MSDN.

**Comment by mmacagno** [comment]
Hello Dobiasd.

Sorry, typo. The error is CS2653.
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2653?view=vs-2019

I agree it's a compiler bug.
The compilation proceeds without issues with VS 16.0.3, but fails with latest versions (16.3.3 and above, as far as I have checked).

I already filed a report with Microsoft, but was wondering whether there was a way to work around this in the meantime... unfortunately I am lost in the complexity of your constructs in result.hpp and have not been able to figure it out.

I am using FPlus indirectly through Eigen and Fdeep.
I don't think compose_results is actually used at all, but simply that part of code will return that error.
I guess I can comment it out for now...

**Comment by Dobiasd** [comment]
That's nice! Thanks for filing [this report](https://developercommunity.visualstudio.com/content/problem/815759/compiler-bug-getting-c2563-error-on-version-1633.html).

> unfortunately I am lost in the complexity of your constructs in result.hpp and have not been able to figure it out.

Yeah, sorry about that. But sometimes I'm also a bit lost my own library. :wink:

And yes, I guess I'd also just comment it out, if I were in your situations. It seems like the easiest and quickest solution right now. Also since hopefully future MSVC versions will hopefully no longer have this problem, this local "fork" should not produce too much additional maintenance effort for you.

**Comment by mmacagno** [comment]
yes, I was able to run successfully after commenting out.
The issue is external and tracked in VS bug database, so I will close this one.

thanks!

**Comment by ralwing** [comment]
@mmacagno Can You point me out to the bug on MS VS bugtracker?

**Comment by mmacagno** [comment]
@ralwing here it is:
https://developercommunity.visualstudio.com/content/problem/815759/compiler-bug-getting-c2563-error-on-version-1633.html
