### ISSUE TITLE
problem with fwd::snd()

### ISSUE THREAD

**Issue by UlfBissbort** [Dobiasd/FunctionalPlus#164]
I'm having a problem using the forward declared version of the `snd` function and could also not find a test case for it. A minimal replicating example 
```
int main() {	
	using namespace fplus;
	using IntPair = std::pair<int, int>;
	const std::vector<IntPair> d = {
		{1,2},
		{3,5},
		{6,8}
	};
	const auto res = fwd::apply(d,	
		fwd::snd()
	);
	return 0;
}
```
which does not compile using g++ 7.4.0 using `g++ -O3 -Wall -std=c++17 demo.cpp -o demo.out` on Ubuntu 18.04.1. This fail with the error 
`error: no matching function for call to ‘snd(const std::vector<std::pair<int, int> >&)’`.

I would have expected 
`fwd::snd()`
to have the same behavior as 
`fwd::transform([](const IntPair& el) { return el.second; })`
and the above code compiles when using the latter instead.

Also, the `snd` function works without the forward declaration, i.e. the code 
```
int main() {
	using namespace fplus;
	const std::pair<int, int> p = {1, 6};
	const auto res = snd(p);
	print_result(res);
	return 0;
}
```
compiles. I'm possibly missing something obvious here, but can't figure it out.

**Comment by Dobiasd** [comment]
Hi. :slightly_smiling_face:

`fplus::snd` is only concerned with pairs, not with any sequence containers:

```cpp
template <typename X, typename Y>
Y snd(const std::pair<X, Y>& pair)
{
    return pair.second;
}
```

`fwd::snd` can be used like this:

```cpp
#include <fplus/fplus.hpp>
int main() {
    using namespace fplus;
    using IntPair = std::pair<int, int>;
    IntPair p = {1, 2};
    const auto res = fwd::apply(p, fwd::snd());
}
```

What you actually want, however, is that:

```cpp
#include <fplus/fplus.hpp>
int main() {
    using namespace fplus;
    using IntPair = std::pair<int, int>;
    const std::vector<IntPair> d = {
        {1,2},
        {3,5},
        {6,8}
    };
    const auto res = fwd::apply(d,
        fwd::transform(fwd::snd())
    );
}
```

**Comment by UlfBissbort** [comment]
Wow, that was fast. That makes sense and I don't know why I didn't try that in hindsight. Thanks for the clarification and the great library in general!
